export const AnimationActionTypes = {

  //below is for CHARACTER
  SET_CHARACTER_POSITION_LEFT: "SET_CHARACTER_POSITION_LEFT",
  SET_CHARACTER_DIRECTION_ANIMATION: "SET_CHARACTER_DIRECTION_ANIMATION",
  END_CHARACTER_ANIMATION:"END_CHARACTER_ANIMATION",
  START_CHARACTER_ANIMATION:"START_CHARACTER_ANIMATION",
  
  // below is for SPEECH BUBBLE
  END_SPEECH_BUBBLE_ANIMATION: "EEND_SPEECH_BUBBLE_ANIMATION",
  START_SPEECH_BUBBLE_ANIMATION: "START_SPEECH_BUBBLE_ANIMATION",
  
}