import React from 'react';
import './about.styles.scss';


const AboutPage = () => {
  return (
    <div className="about-page">
      ABOUT PAGE
      ABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGEABOUT PAGE
    </div>
  )
}

export default AboutPage;