import React from 'react';
import './contact-page.styles.scss';

const ContactPage = () => {
  return(
    <div className="contact-page">
      CONTACT PAGE
      CONTACT PAGECONTACT PAGECONTACT PAGECONTACT PAGECONTACT PAGECONTACT PAGECONTACT PAGECONTACT PAGECONTACT PAGECONTACT PAGECONTACT PAGECONTACT PAGECONTACT PAGECONTACT PAGECONTACT PAGECONTACT PAGECONTACT PAGECONTACT PAGECONTACT PAGECONTACT PAGECONTACT PAGECONTACT PAGECONTACT PAGECONTACT PAGECONTACT PAGECONTACT PAGECONTACT PAGECONTACT PAGECONTACT PAGECONTACT PAGECONTACT PAGE
    </div>
  )
}

export default ContactPage;